#!/usr/bin/env python3
"""
Google Colab Notebook Generator.
Converts code and training configs into a self-contained .ipynb file.
"""

import argparse
import json
import os

def parse_args():
    parser = argparse.ArgumentParser(description="Colab Notebook Generator")
    parser.add_argument("--script", type=str, help="Path to input Python script to convert")
    parser.add_argument("--output", type=str, default="colab_training_notebook.ipynb", help="Output .ipynb filename")
    parser.add_argument("--pip-packages", type=str, default="torch torchvision pandas scikit-learn matplotlib", help="Space-separated pip packages")
    return parser.parse_args()

def create_colab_notebook(script_content, pip_packages, output_path):
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 Auto-Generated Google Colab Training Notebook\n",
                "Generated by Research Agent (`hardware_workload_estimator` skill).\n",
                "\n",
                "> **Note**: Make sure to set GPU runtime: `Runtime -> Change runtime type -> Hardware accelerator -> GPU (T4/V100/A100)`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check GPU Availability\n",
                "!nvidia-smi\n",
                "import torch\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"Device Name: {torch.cuda.get_device_name(0)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                f"# Install Dependencies\n!pip install -q {pip_packages}"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Main Training & Statistical Code\n",
                script_content
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Download Artifacts / Model Weights\n",
                "from google.colab import files\n",
                "import os\n",
                "# Specify files to download back to local machine if needed\n",
                "# files.download('model_weights.pt')\n",
                "print('Training complete! Download results if needed.')"
            ]
        }
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "provenance": []
            },
            "kernelspec": {
                "display_name": "Python 3",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    
    print(f"Colab Notebook successfully generated: {os.path.abspath(output_path)}")

def main():
    args = parse_args()
    script_content = "# Insert training code here\nprint('Hello Colab!')"
    if args.script and os.path.exists(args.script):
        with open(args.script, "r", encoding="utf-8") as f:
            script_content = f.read()
    
    create_colab_notebook(script_content, args.pip_packages, args.output)

if __name__ == "__main__":
    main()
